apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: demo-policy-generator
placementBindingDefaults:
  name: demo-placement-binding
policyDefaults:
  namespace: policies
  placement:
    name: demo-placement-rule
    clusterSelectors:
      vendor: OpenShift
  remediationAction: enforce
  severity: medium
policies:
  - name: policy-app
    manifests:
      - path: policy1
  - name: policy-gatekeeper-require-labels
    consolidateManifests: false
    manifests:
      - path: policy2/install-gatekeeper.yaml
      - path: policy2/gatekeeper.yaml
  - name: policy-kyverno-require-labels
    manifests:
      - path: policy3/kyverno.yaml
