apiVersion: v1
kind: Service
metadata:
  name: gitops-demo
  namespace: gitops-demo
  labels:
    app: gitops-demo
spec:
  ports:
  - name: https
    port: '{{ fromConfigMap "configs" "web-app-config" "service-port" | toInt }}'
    protocol: TCP
    targetPort: 8443
  selector:
    app: gitops-demo
