apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gatekeeper-operator-product
  namespace: openshift-operators
spec:
  channel: stable
  name: gatekeeper-operator-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  mutatingWebhook: Disabled
  validatingWebhook: Enabled
